version: '2'
services:
  php:
    build:
      context: ./docker/php
      args:
        name: my-app-php
    container_name: my-app-php
    volumes:
      - ./:/var/www/html
  nginx:
    build:
      context: ./docker/nginx
      args:
        name: my-app-nginx
    container_name: my-app-nginx
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
