version: '2'
services:
  php:
    build:
      context: ./php
    container_name: my-app-php
    environment:
      - YII_ENV=prod
    volumes:
      - ../../../:/var/www/html
  nginx:
    build:
      context: ./nginx
      args:
        SERVER_NAME: localhost
        PHP_CONTAINER_NAME: my-app-php
    container_name: my-app-nginx
    volumes:
      - ../../../:/var/www/html
    ports:
      - 80:80
